name: riada
description: Riada project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # Common
  path: ^1.9.0
  intl: ^0.19.0
  shared_preferences: ^2.2.3
  decimal: ^3.0.2
  jiffy: ^6.3.1
  form_validator: ^2.1.1
  app_settings: ^5.1.1
  money_formatter: ^0.0.6

  # UI
  cupertino_icons: ^1.0.8
  sizer: ^2.0.15
  carousel_slider: ^5.0.0
  intl_phone_number_input:
    git:
      url: https://github.com/EquiRace/intl_phone_number_input_hint.git
  table_calendar: ^3.1.2
  smooth_page_indicator: ^1.1.0
  pinput: ^5.0.0
  group_list_view: ^1.1.1
  shimmer: ^3.0.0

  # Location
  google_maps_flutter: ^2.7.0
  flutter_geo_hash: ^0.0.4
  geocoding: ^3.0.0

  # Network
  http: ^1.2.1
  json_annotation: ^4.9.0
  webview_flutter: ^4.8.0

  # Image
  flutter_svg: ^2.0.10+1
  cached_network_image: ^3.3.1
  image_picker: ^1.1.2
  flutter_image_compress: ^2.3.0

  # Video
  video_player: ^2.9.1

  # DI, Architecture & Routing
  get_it: ^7.7.0
  injectable: ^2.4.2
  flutter_bloc: ^8.1.6
  auto_route: ^8.2.0
  event_bus: ^2.0.0

  # Firebase
  firebase_core: ^2.32.0
  firebase_analytics: ^10.10.7
  firebase_auth: ^4.20.0
  cloud_functions: ^4.7.6
  firebase_messaging: ^14.9.4
  cloud_firestore: ^4.17.5
  firebase_storage: ^11.7.7
  firebase_dynamic_links: ^5.5.7
  google_sign_in: ^6.2.1
  sign_in_with_apple: ^6.1.1
  crypto: ^3.0.3

  # Notification
  flutter_local_notifications: ^17.2.1

  # Misc
  url_launcher: ^6.3.0

dev_dependencies:
  # generator
  flutter_launcher_icons: ^0.13.1
  auto_route_generator: ^8.0.0
  flutter_gen: ^5.6.0
  json_serializable: ^6.8.0
  injectable_generator: ^2.6.1

  build_runner: ^2.4.11
  flutter_gen_runner: ^5.6.0

flutter_gen:
  integrations:
    flutter_svg: true

flutter_icons:
  image_path: "assets/images/logo.png"
  android: true
  ios: true
  min_sdk_android: 21
  remove_alpha_ios: true

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
    - assets/images/home/
    - assets/images/logo/

  fonts:
    - family: Raleway
      fonts:
        - asset: assets/fonts/Raleway-Regular.ttf
          weight: 400
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Light.ttf
          weight: 300
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700
    - family: Rufina
      fonts:
        - asset: assets/fonts/v2/Rufina-Regular.ttf
          weight: 400
    - family: Inter
      fonts:
        - asset: assets/fonts/v2/Inter-Medium.ttf
          weight: 500