default_platform(:ios)

platform :ios do

  before_all do
    setup_circle_ci
    xcversion(version: "15.3.0")
    api_key = app_store_connect_api_key
    increment_build_number({build_number: latest_testflight_build_number(api_key: api_key) + 1})
    match
  end

  # Lanes
  desc "Push a new prod build to TestFlight"
  lane :prod do
    Dir.chdir "../.." do
        sh("flutter", "packages", "get")
        sh("flutter", "clean")
        sh("flutter", "build", "ios", "-t", "lib/main_prod.dart", "--flavor", "prod", "--release", "--no-codesign")
    end
    build_ios_app(scheme: "prod")
  end

  desc "Push a new staging build to TestFlight"
  lane :staging do
    Dir.chdir "../.." do
        sh("flutter", "packages", "get")
        sh("flutter", "clean")
        sh("flutter", "build", "ios", "-t", "lib/main_staging.dart", "--flavor", "staging", "--release", "--no-codesign")
    end
    build_ios_app(scheme: "staging")
  end

  after_all do
    lane = (lane_context[SharedValues::LANE_NAME] == "ios prod" ? "Prod" : "Staging")
    changelog = "Build " + lane
    upload_to_testflight()
  end
end
